development:
  adapter: postgresql
  encoding: unicode
  database: tiv2_development
  pool: 5
  username: spammo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tiv2_test
  pool: 5
  username: spammo
  password:


